name: ARM builds

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  BUILD_TYPE: Release
  VERBOSE: 1

jobs:
  build-anisette-server-aarch64:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gdc-12-aarch64-linux-gnu dub libz-dev

    - name: Build
      run: dub build :anisette-server -b release --compiler=aarch64-linux-gnu-gdc-12 -c "static"

    - uses: actions/upload-artifact@v3
      with:
        name: anisette-server-aarch64
        path: |
          ${{github.workspace}}/bin/provision_anisette-server
          
  build-anisette-server-armv7:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gdc-12-arm-linux-gnueabihf dub libz-dev

    - name: Build
      run: dub build :anisette-server -b release --compiler=arm-linux-gnueabihf-gdc-12 -c "static"

    - uses: actions/upload-artifact@v3
      with:
        name: anisette-server-armv7
        path: |
          ${{github.workspace}}/bin/provision_anisette-server
