name: x86_64 builds

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  build-anisette-server-x86_64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dub ldc clang libz-dev

      - name: Build
        run: dub build :anisette-server -b release -c "static"

      - uses: actions/upload-artifact@v3
        with:
          name: anisette-server-x86_64
          path: ${{github.workspace}}/bin/provision_anisette-server

  build-anisette-server-i686:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gdc-12-i686-linux-gnu dub

      - name: Build
        run: dub build :anisette-server -b release --compiler=i686-linux-gnu-gdc-12 -c "static"

      - uses: actions/upload-artifact@v3
        with:
          name: anisette-server-i686
          path: ${{github.workspace}}/bin/provision_anisette-server

  build-debug-rh:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dub ldc clang libz-dev

      - name: Build
        run: dub build :retrieve-headers

      - uses: actions/upload-artifact@v3
        with:
          name: retrieve-headers-debug
          path: ${{github.workspace}}/bin/provision_retrieve-headers
